//User
export const SET_USER = 'SET_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

//Ui
export const LOADING_UI = 'LOADING_UI';
export const POSITIVE_MESSAGES = 'POSITIVE_MESSAGES';
export const CLEAR_LOADING_UI = 'CLEAR_LOADING_UI';
export const SET_ERRORS = 'SET_ERRORS';
export const NAVER_DELETED = 'NAVER_DELETED';
export const CLEAR_NAVER_DELETED = 'CLEAR_NAVER_DELETED';

//Navers
export const SET_NAVERS = 'SET_NAVERS';
export const SET_ACTIVE_NAVER = 'SET_ACTIVE_NAVER';
export const CLEAR_ACTIVE_NAVER = 'CLEAR_ACTIVE_NAVER';